source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DTCircleProgressView_Example', :exclusive => true do
  pod "DTCircleProgressView", :path => "../"
end

target 'DTCircleProgressView_Tests', :exclusive => true do
  pod "DTCircleProgressView", :path => "../"

  
end
